[project]
drom-version = "0.1"
share-repo = "https://github.com/OCamlPro/drom-share"
share-version = "0.9.2"

[project]
authors = ["Nicolas Berthier <nicolas.berthier@ocamlpro.com>", "David Declerck <david.declerck@ocamlpro.com>", "Boris Eng <boris.eng@ocamlpro.com>", "Fabrice Le Fessant <fabrice.le_fessant@ocamlpro.com>", "Emilien Lemaire <emilien.lemaire@ocamlpro.com>"]
ci-systems = ["ubuntu-latest", "macos-latest"]
copyright = "OCamlPro SAS"
edition = "4.14.1"
github-organization = "ocamlpro"
license = "MIT"
min-edition = "4.14.0"
name = "superbol-studio-oss"
skeleton = "program"
synopsis = "SuperBOL Studio OSS Project"
version = "0.1.5"
dev-repo = "https://github.com/ocamlpro/superbol-studio-oss"
bug-reports = "https://github.com/ocamlpro/superbol-studio-oss/issues"

# keys that you could also define:
# odoc-target = "...odoc-target..."
# sphinx-target = "...sphinx-target..."
# archive = "...archive..."
# doc-api = "...doc-api..."
# doc-gen = "...doc-gen..."
# homepage = "...homepage..."

[project]
description = """SuperBOL Studio OSS is a new platform for COBOL"""

[project]
skip = ["@test", "@ocamlformat", "@ocp-indent", "README.md", "LICENSE.md", "sphinx/index.rst", "sphinx/install.rst"]

# project-wide library dependencies (not for package-specific deps)
[dependencies]
# NB: now we'd need a way to avoid putting that dependency in `libraries` in `dune` files.
# superbol_testutils = { version = "version", for-test = true }

# project-wide tools dependencies (not for package-specific deps)
[tools]
[tools.odoc]
for-doc = true

[project]

# dirs to skip while scanning for dune files
skip-dirs = ["import", "node_modules"]

# dirs to scan for share/ folders (with package names)
share-dirs = ["share"]

# build profile to use by default
# build-profile = ...

# Profile options for this project
#    [profile]
#    dev = { ocaml-flags = "-w +a-4-40-41-42-44" }
#    release = { ocaml-flags = "-w -a" }
[profile]
dev       = { ocaml-flags = "-w -32-67-69" } #unused value(-declaration), unused field
universal = { ocaml-flags = "-w -32-67-69" }
# ...

# project-wide fields (depends on project skeleton)
# examples:
#  docker-alpine-image = "ocamlpro/ocaml:4.13"
#  dune-lang = "2.1"
#  readme-trailer = "..."
#  dot-gitignore-trailer = "..."
[fields]
dune = "3.17.0"
dot-gitignore-trailer = """
# Edit drom.toml to change the following lines
/superbol-free-*
/dist
/_*
/node_modules
/yarn-error.log
/yarn.lock
/package-json
/gnucobol-config
ATTIC
/out
!.vscode/tasks.json
!.vscode/launch.json
*.vsix
*.opam.locked
/emacs/lsp-superbol-customs.el
"""
github-workflow-before-build = """
      - run: git submodule init

      - run: git submodule update

      - uses: actions/setup-node@v4
        with:
          node-version: '>=16'
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
        if: matrix.build_vsix

"""

# NB: a `before-tests` field would make more sense here.
github-workflow-after-build = """
      - run: make check-package.json

      - run: make dev-deps # install test dependencies
        if: ${{ ! matrix.skip_test }}
"""

github-workflow-after-test = """
      - run: yarn install && npm install esbuild
        if: matrix.build_vsix

      - run: make vsix-debug
        if: matrix.build_vsix

      - name: Upload VSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: VSIX-${{ matrix.os }}
          path: superbol-vscode-platform-*.vsix
          compression-level: 0 # no compression (already a zip archive)
        if: matrix.build_vsix

      - run: make vsix-debug TARGET_PLAT=universal
        if: ${{ matrix.build_vsix && matrix.os == 'ubuntu-latest' }}

      - name: Upload universal VSIX artifact
        uses: actions/upload-artifact@v4
        with:
          name: VSIX-universal
          path: superbol-vscode-platform-*-universal-*.vsix
          compression-level: 0 # no compression (already a zip archive)
        if: ${{ matrix.build_vsix && matrix.os == 'ubuntu-latest' }}
"""

[[package]]
dir = "src/superbol-studio-oss"
# edit 'src/superbol-studio-oss/package.toml' for package-specific options


[[package]]
dir = "src/vscode/superbol-vscode-platform"
# edit 'src/vscode/superbol-vscode-platform/package.toml' for package-specific options

[[package]]
dir = "src/vendor/vscode-ocaml-platform/src-bindings/interop"
# edit 'src/vscode/interop-js-stubs/package.toml' for package-specific options

[[package]]
dir = "src/vendor/vscode-ocaml-platform/src-bindings/node"
# edit 'src/vscode/node-js-stubs/package.toml' for package-specific options

[[package]]
dir = "src/vendor/vscode-ocaml-platform/src-bindings/vscode"
# edit 'src/vscode/vscode-js-stubs/package.toml' for package-specific options

[[package]]
dir = "src/vendor/vscode-ocaml-platform/src-bindings/vscode_languageclient"
# edit 'src/vscode/vscode-languageclient-js-stubs/package.toml' for package-specific options

[[package]]
dir = "src/vscode/vscode-json"
# edit 'src/vscode/vscode-json/package.toml' for package-specific options

[[package]]
dir = "src/vscode/vscode-debugadapter"
# edit 'src/vscode/vscode-debugadapter/package.toml' for package-specific options

[[package]]
dir = "src/vscode/vscode-debugprotocol"
# edit 'src/vscode/vscode-debugprotocol/package.toml' for package-specific options



[[package]]
dir = "src/lsp/superbol-free"
# edit 'src/lsp/superbol/package.toml' for package-specific options

[[package]]
dir = "src/lsp/superbol_free_lib"
# edit 'src/lsp/superbol_lib/package.toml' for package-specific options

[[package]]
dir = "src/lsp/superbol_preprocs"
# edit 'src/lsp/superbol_preprocs/package.toml' for package-specific options

[[package]]
dir = "src/lsp/superbol_project"
# edit 'src/lsp/superbol_project/package.toml' for package-specific options

[[package]]
dir = "src/lsp/cobol_common"
# edit 'src/lsp/cobol_common/package.toml' for package-specific options

[[package]]
dir = "src/lsp/cobol_parser"
# edit 'src/lsp/cobol_parser/package.toml' for package-specific options

[[package]]
dir = "src/lsp/cobol_ptree"
# edit 'src/lsp/cobol_ptree/package.toml' for package-specific options

[[package]]
dir = "src/lsp/ebcdic_lib"
# edit 'src/lsp/ebcdic_lib/package.toml' for package-specific options

[[package]]
dir = "src/lsp/cobol_lsp"
# edit 'src/lsp/cobol_lsp/package.toml' for package-specific options

[[package]]
dir = "src/lsp/ppx_cobcflags"
# edit 'src/lsp/cobol_lsp/package.toml' for package-specific options

[[package]]
dir = "src/lsp/pretty"
# edit 'src/lsp/cobol_lsp/package.toml' for package-specific options

[[package]]
dir = "src/lsp/cobol_config"
# edit 'src/lsp/cobol_lsp/package.toml' for package-specific options

[[package]]
dir = "src/lsp/cobol_indent"
# edit 'src/lsp/cobol_lsp/package.toml' for package-specific options

[[package]]
dir = "src/lsp/cobol_indent_old"
# edit 'src/lsp/cobol_lsp/package.toml' for package-specific options

[[package]]
dir = "src/lsp/cobol_preproc"
# edit 'src/lsp/cobol_lsp/package.toml' for package-specific options

[[package]]
dir = "src/lsp/cobol_data"
# edit 'src/lsp/cobol_lsp/package.toml' for package-specific options

[[package]]
dir = "src/lsp/cobol_typeck"
# edit 'src/lsp/cobol_lsp/package.toml' for package-specific options

[[package]]
dir = "src/lsp/cobol_unit"
# edit 'src/lsp/cobol_unit/package.toml' for package-specific options

[[package]]
dir = "src/vendor/ez_toml"
# edit 'src/testing/superbol_testutils/package.toml' for package-specific options

[[package]]
dir = "src/lsp/ezr_toml"
# edit 'src/lsp/ezr_toml/package.toml' for package-specific options

[[package]]
dir = "src/lsp/sql_preproc"
# edit 'src/lsp/ezr_toml/package.toml' for package-specific options

[[package]]
dir = "src/lsp/sql_ast"
# edit 'src/lsp/sql_ast/package.toml' for package-specific options

[[package]]
dir = "src/lsp/sql_parser"
# edit 'src/lsp/sql_parser/package.toml' for package-specific options

[[package]]
dir = "src/lsp/cobol_cfg"
